packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@hookform/resolvers": 3.9.1
  "@supabase/supabase-js": 2.46.0
  "@t3-oss/env-nextjs": 0.11.1
  "@tanstack/react-query": 5.59.16
  "@trpc/client": 11.0.0-rc.477
  "@trpc/react-query": 11.0.0-rc.477
  "@trpc/server": 11.0.0-rc.477
  "@types/node": 22.8.2
  "@types/react": 18.3.12
  "@types/react-dom": 18.3.1
  "@types/react-responsive-masonry": 2.1.3
  "@types/uuid": 10.0.0
  autoprefixer: 10.4.20
  date-fns: 4.1.0
  dotenv-cli: 7.4.2
  eslint: 9.13.0
  jiti: 2.3.3
  lucide-react: 0.454.0
  next: 15.0.1
  next-themes: 0.3.0
  superjson: 2.2.1
  postcss: 8.4.47
  postcss-load-config: 6.0.1
  prettier: 3.3.3
  react: 19.0.0-rc-6cf85185-20241014
  react-dom: 19.0.0-rc-6cf85185-20241014
  react-hook-form: 7.53.1
  react-responsive-masonry: 2.4.1
  sonner: 1.5.0
  tailwindcss: 3.4.14
  typescript: 5.6.3
  uuid: 11.0.2
  zod: 3.23.8
